{"id":"21686146399","type":"IssueCommentEvent","actor":{"id":3732628,"login":"fredericoschardong","display_login":"fredericoschardong","gravatar_id":"","url":"https://api.github.com/users/fredericoschardong","avatar_url":"https://avatars.githubusercontent.com/u/3732628?"},"repo":{"id":162497174,"name":"open-quantum-safe/liboqs-python","url":"https://api.github.com/repos/open-quantum-safe/liboqs-python"},"payload":{"action":"created","issue":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48","repository_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python","labels_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48/labels{/name}","comments_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48/comments","events_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48/events","html_url":"https://github.com/open-quantum-safe/liboqs-python/issues/48","id":1228658487,"node_id":"I_kwDOCa-Cls5JO9c3","number":48,"title":"Can't pip install from docker container","user":{"login":"fredericoschardong","id":3732628,"node_id":"MDQ6VXNlcjM3MzI2Mjg=","avatar_url":"https://avatars.githubusercontent.com/u/3732628?v=4","gravatar_id":"","url":"https://api.github.com/users/fredericoschardong","html_url":"https://github.com/fredericoschardong","followers_url":"https://api.github.com/users/fredericoschardong/followers","following_url":"https://api.github.com/users/fredericoschardong/following{/other_user}","gists_url":"https://api.github.com/users/fredericoschardong/gists{/gist_id}","starred_url":"https://api.github.com/users/fredericoschardong/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/fredericoschardong/subscriptions","organizations_url":"https://api.github.com/users/fredericoschardong/orgs","repos_url":"https://api.github.com/users/fredericoschardong/repos","events_url":"https://api.github.com/users/fredericoschardong/events{/privacy}","received_events_url":"https://api.github.com/users/fredericoschardong/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2022-05-07T15:46:05Z","updated_at":"2022-05-09T11:29:07Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Hey,\r\n\r\nIs it a bug or a feature that we can't use pip install with liboqs-pythons' docker? Or am I missing something? For instance, take the following Dockerfile as an example. If I don't use the intermediary `pre_quantum` to copy `libssl.so.1.1` and `libcrypto.so.1.1`, then I get the errors listed below. \r\n\r\n```\r\nFROM alpine:3.11 as pre_quantum\r\n\r\nRUN apk update && apk add openssl\r\n\r\nFROM openquantumsafe/python\r\n\r\nCOPY app /app\r\nWORKDIR /app\r\n\r\nUSER root\r\nRUN apk update && apk add python3-dev gcc libc-dev libffi-dev\r\n\r\nCOPY --from=pre_quantum /lib/libssl.so.1.1 /lib/libssl.so.1.1\r\nCOPY --from=pre_quantum /lib/libcrypto.so.1.1 /lib/libcrypto.so.1.1\r\n\r\nRUN pip3 install --no-cache --upgrade pip setuptools\r\nRUN pip3 install -r requirements.txt\r\n```\r\n\r\n\r\n```\r\nWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))': /simple/pip/\r\nWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))': /simple/pip/\r\nWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))': /simple/pip/\r\nWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))': /simple/pip/\r\nWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))': /simple/pip/\r\nCould not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))) - skipping\r\n```","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48/timeline","performed_via_github_app":null},"comment":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/comments/1120979091","html_url":"https://github.com/open-quantum-safe/liboqs-python/issues/48#issuecomment-1120979091","issue_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48","id":1120979091,"node_id":"IC_kwDOCa-Cls5C0MiT","user":{"login":"fredericoschardong","id":3732628,"node_id":"MDQ6VXNlcjM3MzI2Mjg=","avatar_url":"https://avatars.githubusercontent.com/u/3732628?v=4","gravatar_id":"","url":"https://api.github.com/users/fredericoschardong","html_url":"https://github.com/fredericoschardong","followers_url":"https://api.github.com/users/fredericoschardong/followers","following_url":"https://api.github.com/users/fredericoschardong/following{/other_user}","gists_url":"https://api.github.com/users/fredericoschardong/gists{/gist_id}","starred_url":"https://api.github.com/users/fredericoschardong/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/fredericoschardong/subscriptions","organizations_url":"https://api.github.com/users/fredericoschardong/orgs","repos_url":"https://api.github.com/users/fredericoschardong/repos","events_url":"https://api.github.com/users/fredericoschardong/events{/privacy}","received_events_url":"https://api.github.com/users/fredericoschardong/received_events","type":"User","site_admin":false},"created_at":"2022-05-09T11:29:07Z","updated_at":"2022-05-09T11:29:07Z","author_association":"NONE","body":"Thank you, @baentsch. I see you have already pushed this fix to the docker hub. Would it be possible to version the images instead of only pushing changes to `:latest`? Although the fix is welcomed, it broke our pipeline. It would be great if we had some time to adapt.","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/comments/1120979091/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null}},"public":true,"created_at":"2022-05-09T11:29:07Z","org":{"id":20689385,"login":"open-quantum-safe","gravatar_id":"","url":"https://api.github.com/orgs/open-quantum-safe","avatar_url":"https://avatars.githubusercontent.com/u/20689385?"}}
{"id":"21686849880","type":"IssueCommentEvent","actor":{"id":57787676,"login":"baentsch","display_login":"baentsch","gravatar_id":"","url":"https://api.github.com/users/baentsch","avatar_url":"https://avatars.githubusercontent.com/u/57787676?"},"repo":{"id":162497174,"name":"open-quantum-safe/liboqs-python","url":"https://api.github.com/repos/open-quantum-safe/liboqs-python"},"payload":{"action":"created","issue":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48","repository_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python","labels_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48/labels{/name}","comments_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48/comments","events_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48/events","html_url":"https://github.com/open-quantum-safe/liboqs-python/issues/48","id":1228658487,"node_id":"I_kwDOCa-Cls5JO9c3","number":48,"title":"Can't pip install from docker container","user":{"login":"fredericoschardong","id":3732628,"node_id":"MDQ6VXNlcjM3MzI2Mjg=","avatar_url":"https://avatars.githubusercontent.com/u/3732628?v=4","gravatar_id":"","url":"https://api.github.com/users/fredericoschardong","html_url":"https://github.com/fredericoschardong","followers_url":"https://api.github.com/users/fredericoschardong/followers","following_url":"https://api.github.com/users/fredericoschardong/following{/other_user}","gists_url":"https://api.github.com/users/fredericoschardong/gists{/gist_id}","starred_url":"https://api.github.com/users/fredericoschardong/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/fredericoschardong/subscriptions","organizations_url":"https://api.github.com/users/fredericoschardong/orgs","repos_url":"https://api.github.com/users/fredericoschardong/repos","events_url":"https://api.github.com/users/fredericoschardong/events{/privacy}","received_events_url":"https://api.github.com/users/fredericoschardong/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":2,"created_at":"2022-05-07T15:46:05Z","updated_at":"2022-05-09T12:09:17Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Hey,\r\n\r\nIs it a bug or a feature that we can't use pip install with liboqs-pythons' docker? Or am I missing something? For instance, take the following Dockerfile as an example. If I don't use the intermediary `pre_quantum` to copy `libssl.so.1.1` and `libcrypto.so.1.1`, then I get the errors listed below. \r\n\r\n```\r\nFROM alpine:3.11 as pre_quantum\r\n\r\nRUN apk update && apk add openssl\r\n\r\nFROM openquantumsafe/python\r\n\r\nCOPY app /app\r\nWORKDIR /app\r\n\r\nUSER root\r\nRUN apk update && apk add python3-dev gcc libc-dev libffi-dev\r\n\r\nCOPY --from=pre_quantum /lib/libssl.so.1.1 /lib/libssl.so.1.1\r\nCOPY --from=pre_quantum /lib/libcrypto.so.1.1 /lib/libcrypto.so.1.1\r\n\r\nRUN pip3 install --no-cache --upgrade pip setuptools\r\nRUN pip3 install -r requirements.txt\r\n```\r\n\r\n\r\n```\r\nWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))': /simple/pip/\r\nWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))': /simple/pip/\r\nWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))': /simple/pip/\r\nWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))': /simple/pip/\r\nWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))': /simple/pip/\r\nCould not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))) - skipping\r\n```","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48/timeline","performed_via_github_app":null},"comment":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/comments/1121016380","html_url":"https://github.com/open-quantum-safe/liboqs-python/issues/48#issuecomment-1121016380","issue_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48","id":1121016380,"node_id":"IC_kwDOCa-Cls5C0Vo8","user":{"login":"baentsch","id":57787676,"node_id":"MDQ6VXNlcjU3Nzg3Njc2","avatar_url":"https://avatars.githubusercontent.com/u/57787676?v=4","gravatar_id":"","url":"https://api.github.com/users/baentsch","html_url":"https://github.com/baentsch","followers_url":"https://api.github.com/users/baentsch/followers","following_url":"https://api.github.com/users/baentsch/following{/other_user}","gists_url":"https://api.github.com/users/baentsch/gists{/gist_id}","starred_url":"https://api.github.com/users/baentsch/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/baentsch/subscriptions","organizations_url":"https://api.github.com/users/baentsch/orgs","repos_url":"https://api.github.com/users/baentsch/repos","events_url":"https://api.github.com/users/baentsch/events{/privacy}","received_events_url":"https://api.github.com/users/baentsch/received_events","type":"User","site_admin":false},"created_at":"2022-05-09T12:09:17Z","updated_at":"2022-05-09T12:09:17Z","author_association":"MEMBER","body":"The push to `:latest` happens automatically when CI passes -- and a bit prematurely considering the PR has not received review (now fixed).... Sorry we didn't yet have others' automated/pipeline use of the image in mind. \r\n\r\nWe surely could (also) add tags to images \"past\". In the absence of an automated versioning system for `liboqs-python` and the dockerfile the most simple way would be to use the git commit ID as tag: Would that suffice for you, @fredericoschardong or do you have other suggestions?\r\n\r\nQuestion to @vsoftco : Would you prefer a specific versioning scheme for the project? The current `setup.py` contains \"string-reference\" to (liboqs?) version 0.7.1 but the actual liboqs built can be/is different (0.7.2-dev, currently). Suggestions how to version docker images \"on top\" very welcome.","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/comments/1121016380/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null}},"public":true,"created_at":"2022-05-09T12:09:17Z","org":{"id":20689385,"login":"open-quantum-safe","gravatar_id":"","url":"https://api.github.com/orgs/open-quantum-safe","avatar_url":"https://avatars.githubusercontent.com/u/20689385?"}}
{"id":"21693971752","type":"IssueCommentEvent","actor":{"id":3732628,"login":"fredericoschardong","display_login":"fredericoschardong","gravatar_id":"","url":"https://api.github.com/users/fredericoschardong","avatar_url":"https://avatars.githubusercontent.com/u/3732628?"},"repo":{"id":162497174,"name":"open-quantum-safe/liboqs-python","url":"https://api.github.com/repos/open-quantum-safe/liboqs-python"},"payload":{"action":"created","issue":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48","repository_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python","labels_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48/labels{/name}","comments_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48/comments","events_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48/events","html_url":"https://github.com/open-quantum-safe/liboqs-python/issues/48","id":1228658487,"node_id":"I_kwDOCa-Cls5JO9c3","number":48,"title":"Can't pip install from docker container","user":{"login":"fredericoschardong","id":3732628,"node_id":"MDQ6VXNlcjM3MzI2Mjg=","avatar_url":"https://avatars.githubusercontent.com/u/3732628?v=4","gravatar_id":"","url":"https://api.github.com/users/fredericoschardong","html_url":"https://github.com/fredericoschardong","followers_url":"https://api.github.com/users/fredericoschardong/followers","following_url":"https://api.github.com/users/fredericoschardong/following{/other_user}","gists_url":"https://api.github.com/users/fredericoschardong/gists{/gist_id}","starred_url":"https://api.github.com/users/fredericoschardong/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/fredericoschardong/subscriptions","organizations_url":"https://api.github.com/users/fredericoschardong/orgs","repos_url":"https://api.github.com/users/fredericoschardong/repos","events_url":"https://api.github.com/users/fredericoschardong/events{/privacy}","received_events_url":"https://api.github.com/users/fredericoschardong/received_events","type":"User","site_admin":false},"labels":[],"state":"open","locked":false,"assignee":null,"assignees":[],"milestone":null,"comments":3,"created_at":"2022-05-07T15:46:05Z","updated_at":"2022-05-09T18:06:32Z","closed_at":null,"author_association":"NONE","active_lock_reason":null,"body":"Hey,\r\n\r\nIs it a bug or a feature that we can't use pip install with liboqs-pythons' docker? Or am I missing something? For instance, take the following Dockerfile as an example. If I don't use the intermediary `pre_quantum` to copy `libssl.so.1.1` and `libcrypto.so.1.1`, then I get the errors listed below. \r\n\r\n```\r\nFROM alpine:3.11 as pre_quantum\r\n\r\nRUN apk update && apk add openssl\r\n\r\nFROM openquantumsafe/python\r\n\r\nCOPY app /app\r\nWORKDIR /app\r\n\r\nUSER root\r\nRUN apk update && apk add python3-dev gcc libc-dev libffi-dev\r\n\r\nCOPY --from=pre_quantum /lib/libssl.so.1.1 /lib/libssl.so.1.1\r\nCOPY --from=pre_quantum /lib/libcrypto.so.1.1 /lib/libcrypto.so.1.1\r\n\r\nRUN pip3 install --no-cache --upgrade pip setuptools\r\nRUN pip3 install -r requirements.txt\r\n```\r\n\r\n\r\n```\r\nWARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))': /simple/pip/\r\nWARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))': /simple/pip/\r\nWARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))': /simple/pip/\r\nWARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))': /simple/pip/\r\nWARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))': /simple/pip/\r\nCould not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLError(1, '[SSL: UNEXPECTED_MESSAGE] unexpected message (_ssl.c:1131)'))) - skipping\r\n```","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"timeline_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48/timeline","performed_via_github_app":null},"comment":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/comments/1121414528","html_url":"https://github.com/open-quantum-safe/liboqs-python/issues/48#issuecomment-1121414528","issue_url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/48","id":1121414528,"node_id":"IC_kwDOCa-Cls5C122A","user":{"login":"fredericoschardong","id":3732628,"node_id":"MDQ6VXNlcjM3MzI2Mjg=","avatar_url":"https://avatars.githubusercontent.com/u/3732628?v=4","gravatar_id":"","url":"https://api.github.com/users/fredericoschardong","html_url":"https://github.com/fredericoschardong","followers_url":"https://api.github.com/users/fredericoschardong/followers","following_url":"https://api.github.com/users/fredericoschardong/following{/other_user}","gists_url":"https://api.github.com/users/fredericoschardong/gists{/gist_id}","starred_url":"https://api.github.com/users/fredericoschardong/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/fredericoschardong/subscriptions","organizations_url":"https://api.github.com/users/fredericoschardong/orgs","repos_url":"https://api.github.com/users/fredericoschardong/repos","events_url":"https://api.github.com/users/fredericoschardong/events{/privacy}","received_events_url":"https://api.github.com/users/fredericoschardong/received_events","type":"User","site_admin":false},"created_at":"2022-05-09T18:06:32Z","updated_at":"2022-05-09T18:06:32Z","author_association":"NONE","body":"> We surely could (also) add tags to images \"past\". In the absence of an automated versioning system for `liboqs-python` and the dockerfile the most simple way would be to use the git commit ID as tag: Would that suffice for you, @fredericoschardong or do you have other suggestions?\r\n\r\nAny versioning works for me. Although not very human, git commit ID is ok.","reactions":{"url":"https://api.github.com/repos/open-quantum-safe/liboqs-python/issues/comments/1121414528/reactions","total_count":0,"+1":0,"-1":0,"laugh":0,"hooray":0,"confused":0,"heart":0,"rocket":0,"eyes":0},"performed_via_github_app":null}},"public":true,"created_at":"2022-05-09T18:06:32Z","org":{"id":20689385,"login":"open-quantum-safe","gravatar_id":"","url":"https://api.github.com/orgs/open-quantum-safe","avatar_url":"https://avatars.githubusercontent.com/u/20689385?"}}
